# Generated by Django 5.0.6 on 2024-09-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_data', '0006_remove_results_item_results_test_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='test_to',
            field=models.TextField(blank=True, choices=[('BREB', 'BREB'), ('PBS', 'PBS')], null=True),
        ),
    ]
