# Generated by Django 5.0.6 on 2024-11-23 03:01

import accounts.models
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(blank=True, max_length=255, null=True)),
                ('office_code', models.CharField(default='0', max_length=10, null=True)),
                ('catagory', models.CharField(blank=True, choices=[('head_quater', 'HQ'), ('zonal', 'ZO'), ('sub_zonal', 'SZO')], max_length=150, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('pbs_name', models.CharField(blank=True, default='default_pbs', max_length=150, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('MT', 'MT'), ('MTS', 'MTS'), ('IT', 'IT'), ('AGM', 'AGM'), ('DGM', 'DGM'), ('BS', 'BS'), ('BA', 'BA'), ('JE', 'JE'), ('LT', 'LT'), ('LM', 'LM'), ('user', 'User')], default='user', max_length=10)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('training_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('date', models.DateField(default=accounts.models.today)),
                ('sign_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.designation')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.office')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='pbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.pbs'),
        ),
        migrations.CreateModel(
            name='Standard_Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_serial', models.CharField(blank=True, max_length=20, null=True)),
                ('std_name', models.CharField(blank=True, max_length=20, null=True)),
                ('std_kh', models.CharField(blank=True, max_length=5, null=True)),
                ('from_date', models.DateField(default='2024-11-23')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('office', models.ForeignKey(blank=True, default=accounts.models.default_office, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.office')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_checked_by', to=settings.AUTH_USER_MODEL)),
                ('counter_sign_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_counter_sign_by', to=settings.AUTH_USER_MODEL)),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.office')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_received_by', to=settings.AUTH_USER_MODEL)),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_tested_by', to=settings.AUTH_USER_MODEL)),
                ('standered_meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.standard_meter')),
            ],
        ),
    ]
