# Generated by Django 5.0.6 on 2024-11-23 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard_meter',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
