# Generated by Django 5.0.6 on 2024-11-23 06:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_standard_meter_from_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard_meter',
            name='from_date',
            field=models.DateField(default=accounts.models.today),
        ),
    ]
