# Generated by Django 5.0.6 on 2024-08-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_sidebar_alter_customuser_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sidebar',
        ),
    ]
