# Generated by Django 5.0.6 on 2024-08-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date',
            field=models.DateField(default='2024-08-13'),
        ),
        migrations.AlterField(
            model_name='standard_meter',
            name='from_date',
            field=models.DateField(default='2024-08-13'),
        ),
    ]
