# Generated by Django 5.0.6 on 2024-08-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_updated_by_alter_customuser_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date',
            field=models.DateField(default='2024-08-15'),
        ),
        migrations.AlterField(
            model_name='standard_meter',
            name='from_date',
            field=models.DateField(default='2024-08-15'),
        ),
    ]
