# Generated by Django 5.0.6 on 2024-11-23 03:01

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=100, unique=True)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_start', models.CharField(blank=True, max_length=10, null=True)),
                ('sl_end', models.CharField(blank=True, max_length=10, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('store_return_ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket_no', models.CharField(blank=True, max_length=50, null=True)),
                ('referance_name', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('debit_qty', models.IntegerField(default=0)),
                ('credit_qty', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_created_by', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(default=accounts.models.default_office, on_delete=django.db.models.deletion.CASCADE, to='accounts.office')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_updated_by', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='balance_reg.item')),
            ],
            options={
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='SealBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, default='J-31', max_length=10, null=True)),
                ('sl_start', models.CharField(blank=True, max_length=10, null=True)),
                ('sl_end', models.CharField(blank=True, max_length=10, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('store_return_ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket_no', models.CharField(blank=True, max_length=50, null=True)),
                ('referance_name', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('debit_qty', models.IntegerField(default=0)),
                ('credit_qty', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seal_balance_created_by', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(default=accounts.models.default_office, on_delete=django.db.models.deletion.CASCADE, to='accounts.office')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seal_balance_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_start'],
            },
        ),
    ]
