# Generated by Django 5.0.6 on 2024-08-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_reg', '0002_balance_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='sealbalance',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
